Repository CSCI-GA-2820-FA22-003/shopcarts, pull requests merged in 2022-12, with the labels that each got.

#103 Update frontend layout
  service/static/index.html
Labels: enhancement

#114 Migrate to a new cluster
  Makefile
Labels: Technical Debt

#119 Documentation
  README.md
  docs/items/add.md
  docs/items/delete.md
  docs/items/list.md
  docs/items/read.md
  docs/items/update.md
  docs/shopcarts/create.md
  docs/shopcarts/delete.md
  docs/shopcarts/read.md
  docs/shopcarts/read_all.md
  docs/shopcarts/update.md
Labels: documentation

#121 Add features to query products in ascending/descending order by time
  features/shopcart.feature
  service/models.py
  service/static/index.html
  tests/test_models.py
  tests/test_routes.py
Labels: enhancement
