Repository CSCI-GA-2820-FA22-003/shopcarts, pull requests merged in 2022-11, with the labels that each got.

#73 Link readme
  README.md
Labels: documentation

#74 User interface for bdd
  README.md
  features/environment.py
  service/routes.py
  service/static/css/blue_bootstrap.min.css
  service/static/css/cerulean_bootstrap.min.css
  service/static/css/darkly_bootstrap.min.css
  service/static/css/flatly_bootstrap.min.css
  service/static/css/slate_bootstrap.min.css
  service/static/images/newapp-icon.png
  service/static/index.html
  service/static/js/bootstrap.min.js
  service/static/js/jquery-3.6.0.min.js
  service/static/js/rest_api.js
Labels: enhancement

#76 Move checks to model
  service/models.py
  service/routes.py
  tests/test_models.py
  tests/test_routes.py
Labels: Technical Debt

#77 Add IBM cloud CLI and health check
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/scripts/install-tools.sh
  Makefile
  dot-env-example
  manifest.yml
  scripts/copy-apikey.sh
  service/routes.py
Labels: enhancement, Technical Debt

#85 Allow query for product using max-price and min-price
  service/models.py
  service/routes.py
  tests/test_models.py
  tests/test_routes.py
Labels: enhancement

#88 Add bdd tests, refactor code to comply
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/bdd.yml
  .vscode/settings.json
  .vscode/tasks.json
  Pipfile
  Pipfile.lock
  Vagrantfile
  dot-env-example
  features/shopcart.feature
  features/steps/product_steps.py
  features/steps/steps.py
  requirements.txt
  service/models.py
  service/static/index.html
  service/static/js/rest_api.js
Labels: Technical Debt

#96 Add BDD test for delete
  features/shopcart.feature
Labels: enhancement

#98 Bdd query action
  features/shopcart.feature
  service/static/index.html
  service/static/js/rest_api.js
Labels: Technical Debt
