Repository CSCI-GA-2820-FA22-003/shopcarts, pull requests merged in 2022-10, with the labels that each got.

#34 Create model for products and tests for products
  service/models.py
  service/routes.py
  tests/factories.py
  tests/test_models.py
Labels: enhancement

#35 Revert "Create model for products and tests for products"
  service/models.py
  service/routes.py
  tests/factories.py
  tests/test_models.py
Labels: bug

#36 Add Products model and part of Shopcarts model. Fixed some potential bugs. Fixed all formatting errors.
  service/__init__.py
  service/common/cli_commands.py
  service/models.py
  service/routes.py
  tests/factories.py
  tests/test_cli_commands.py
  tests/test_models.py
Labels: bug, enhancement

#37 Finish adding shopcart models and test cases for all models
  README.md
  service/models.py
  service/routes.py
  tests/factories.py
  tests/test_models.py
Labels: documentation, enhancement

#45 Update a shopcart
  .devcontainer/devcontainer.json
  .vscode/settings.json
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#44 Develop a REST API service to Delete a shopcart from the service
  service/routes.py
  tests/test_routes.py
Labels: enhancement

#46 Add comments for all REST APIs
  service/routes.py
Labels: Technical Debt

#49 Update README.md to document all the end-point and usage
  README.md
  service/routes.py
Labels: documentation

#51 Add missing comment for tests
  tests/test_routes.py
Labels: bug

#53 Add test cases
  tests/test_routes.py
Labels: documentation

#58 Ci setup
  .github/workflows/workflow.yml
  requirements.txt
  tests/test_cli_commands.py
Labels: enhancement

#60 Codecov report
  .github/workflows/workflow.yml
  setup.cfg
Labels: enhancement

#62 Update README.md to add codecov badge
  README.md
Labels: documentation

#63 Change linting config and fixed pylint errors under tests directory
  .github/workflows/workflow.yml
  Makefile
  service/__init__.py
  service/routes.py
  tests/factories.py
  tests/test_cli_commands.py
  tests/test_models.py
  tests/test_routes.py
Labels: bug, enhancement
